### ISSUE TITLE
System beep after certain commands

### ISSUE THREAD

**Issue by predmijat** [oh-my-fish/theme-budspencer#10]
Hey,

I don't know if this is desired behavior or not, but I can hear system beep after commands like ls, touch, cat, cp, rm, maybe some others...there is no beep on cd though. I've test both with and without my custom (before).init.fish, and result is the same. I don't experience this with default theme, nor with "agnoster" theme which I've also used.

Should it be like that? If yes, how do I turn it off? If not, how can I debug it?

Thanks!

**Comment by bpinto** [comment]
I wonder if somewhere we are doing this: `echo -e "\a"` which would make a beep sound.

**Comment by bpinto** [comment]
Lol, look what I found: https://github.com/oh-my-fish/theme-budspencer/blob/master/fish_prompt.fish#L226

@predmijat Could you remove this line and see if the beep stops?

**Comment by predmijat** [comment]
Yup, that fixes it...nice find :)

**Comment by bpinto** [comment]
I don't know why it was added though. :D

**Comment by bobthecow** [comment]
It was introduced in 4e6a213eaf069eb21a3e4baadf70b1ef05e3124c … looks like debugging output that snuck in? @tannhuber?

**Comment by bobthecow** [comment]
Or maybe :trollface:

**Comment by tannhuber** [comment]
This is desired behaviour. I use the visual bell to set the X11 urgency hint flag. The window manager then tells me when a time consuming job has finished.

Example from my daily life: I'm doing data analysis with a R-script. This might take some hours. The job runs in a workspace for time consuming jobs. The status bar tells me there's something running in the last workspace (blue sand glass symbol). 
![scrot-2015-11-03-205521](https://cloud.githubusercontent.com/assets/2333069/10920262/7c5445a2-826f-11e5-86c6-24b82bf9f3d8.png)

When the job is done, the urgency hint flag is set. The sand glass becomes red.
![scrot-2015-11-03-205821](https://cloud.githubusercontent.com/assets/2333069/10920288/9dec9642-826f-11e5-9772-7a8c89b3651e.png)


The same happens with the window title bar.
![2015-11-03-210946_1366x768_scrot](https://cloud.githubusercontent.com/assets/2333069/10920300/a95fa6b8-826f-11e5-9b07-f5196d26cb94.png)


There's even a shortcut to quickly jump to a window with an urgency hint flag. I don't want to miss that feature anymore. It's very useful.

I didn't know that there're still people that haven't deactivated the acoustic beep.

**Comment by predmijat** [comment]
I actually thought that it might be something like that, but I wanted to be sure that it's not some function or whetever which can't work because of x and instead just sends a beep :) I'll close it, thanks for the explanation!

**Comment by tannhuber** [comment]
Probably, most people don't know about the urgency hint flag although it's an ICCCM standard feature. So, it might be a good idea to make it configurable. Let's reopen the issue until it's implemented as an option.

**Comment by tannhuber** [comment]
Done. `set -U budspencer_nobell` should switch the bell off.

**Comment by bobthecow** [comment]
@tannhuber We've started making theme configuration names a bit more generic in the hopes that more options will become portable across themes. The convention is to use a `theme_` prefix. Let's use that for this option as well?

**Comment by bpinto** [comment]
I am jealous of your terminal @tannhuber 
I want that!!!

**Comment by tannhuber** [comment]
@bobthecow Good to know. I agree, it's a good idea to change these lines. As a reminder, I'd like to reopen the issue again. I'll check how it's done in bobthefish theme.

@bpinto The statusbar is [dzen2][1]. I'm not sure if it's a good choice for you. It's crucial to be a nerd in order to use it. ;-)

[1]: https://github.com/robm/dzen

**Comment by tannhuber** [comment]
Done.

**Comment by JewsOfHazard** [comment]
This still happens for me and I don't know how to fix it.

**Comment by clayauld** [comment]
Please read the README for the repo. To turn off the terminal bell, add this to your init.fish

```
set -U budspencer_nobell
```
