### ISSUE TITLE
Some functionality broken with latest fish shell

### ISSUE THREAD

**Issue by motdef** [oh-my-fish/theme-budspencer#17]
Sorry for the slightly ambiguous title but I don't know specifically what to call this functionality; previously, budspencer would keep cd commands on the same line, not accept an empty string as a command, prompt you for a correction if you tried to cd into a non-existent directory etc, but I seem to have lost these nice features after updating fish.

**Comment by tannhuber** [comment]
You're right, see fish-shell/fish-shell@d65c633. The theme should be adapted.

**Comment by tannhuber** [comment]
@motdef Thank you.
