### ISSUE TITLE
Malfunction when overriding greeting function

### ISSUE THREAD

**Issue by abijr** [oh-my-fish/theme-budspencer#18]
If I override the `fish_greeting` function, the fish prompt warns about missing `__budspencer_urgency` function, and I cannot use the `wt` function. I suspect other functions/variables from the `fish_greeting.fish` file are not loaded/set, but I haven't investigated further.

Any workarounds for this? I'd really like to set my own greeting function.

I have an idea, and I can submit a PR. It's basically an `if` in the `fish_greeting` function that runs another function, if a variable is set (probably something like `__budspencer_greeting_override`). But perhaps there is a simpler solution for this.

**Comment by tannhuber** [comment]
Hi @abijr: I think, the definitions within `fish_greeting.fish` should go into `fish_prompt.fish`. It's a design bug. I'll check it and provide a bug fix as soon as possible.

**Comment by abijr** [comment]
It works! Thanks!
