### ISSUE TITLE
Upgrade to Fisherman

### ISSUE THREAD

**Issue by bucaran** [oh-my-fish/theme-budspencer#19]
Hi @tannhuber!

Would you like to take a look at [Fisherman](https://github.com/fisherman/fisherman) and let me know if you would like to have Budspencer integrated out of the box?

Thanks

**Comment by tannhuber** [comment]
As a zsh user, I started budspencer theme for oh-my-zsh, then changed to prezto. When I switched to fish, I moved the theme to oh-my-fish and tacklebox.

At the moment, I don't see the necessity to provide it to another project. Oh-my-fish gives me all the freedom I need as originator and main developer of the theme.
