### ISSUE TITLE
Budspencer should be temporarily disabled when switching to TTY.

### ISSUE THREAD

**Issue by raphael-costa** [oh-my-fish/theme-budspencer#21]
I was able to solve this problem in my local installation by adding this to config.fish: 

       if test (tput colors) = 256
          omf theme budspencer
        else
          omf theme default

A (better, more professional) solution should probably be added to the defaults.

**Comment by tannhuber** [comment]
You're right. If it's just a color issue, you can
```set -U budspencer_colors blue green magenta ...```
But probably there're more things not working in a tty.
You could also try fbterm if you are allowed.
