### ISSUE TITLE
Changing the text color

### ISSUE THREAD

**Issue by predmijat** [oh-my-fish/theme-budspencer#22]
Hi,

I've posted this originally here - https://groups.google.com/forum/#!topic/iterm2-discuss/2c1u2eZywgE

I'm trying to change the text color (input text, e.g. "set budspencer_colors ..." - "set" is dark blue, and the rest is light blue no matter what I change - budspencer_colors to all 0's, the whole theme, the iTerm color settings - nothing works. So, what controls the color of "input" text?

Thanks

**Comment by tannhuber** [comment]
If I understand you correctly, you would like to change the fish colors `$fish_color_`something.
Type
```
echo $fish_color_<Tab>
```
to check your current settings. Alternatively you can use `fish_config`.

**Comment by predmijat** [comment]
That's it...thanks @tannhuber

**Comment by tannhuber** [comment]
@predmijat For completeness, you could leave a short comment in the previously mentioned mailing list. It may be helpful to others.
