### ISSUE TITLE
Crashes

### ISSUE THREAD

**Issue by base698** [oh-my-fish/theme-budspencer#26]
$ fish
This is budspencer theme for fish, a theme for the 70s.
Type »budspencer_help« in order to see how you can speed up your workflow.
Assertion failed: (false), function builtin_end, file builtin.cpp, line 3549.
Abort trap: 6

**Comment by tannhuber** [comment]
May I help you? What's the problem?

**Comment by clayauld** [comment]
old issue with no response. Closing it now.
