### ISSUE TITLE
Enter works for some installations and does not work for some.

### ISSUE THREAD

**Issue by kmskrishna** [oh-my-fish/theme-budspencer#27]
I used to get this weird error previously where you cannot press enter with out any command in the terminal. Later when I installed it in some other system it resolved it self.

The counter does not increase if you press enter like it happens normally. it only increases if you type a command. Not only the counter, the line does not go down which usually happens.

**Comment by tannhuber** [comment]
Hi @Eta-Meson,

I think you use an "old" fish version, do you? The newline behavior changed in Dez 2015, see #17.

**Comment by Eta-Meson** [comment]
I am currently using version 2.2.0-830-gfb1443a

**Comment by tannhuber** [comment]
I'm sorry, I cannot identify your version. gfb1443a differs from all github version numbers. Anyway, can you check, your fish-shell is newer than https://github.com/fish-shell/fish-shell/commit/d65c633?

**Comment by clayauld** [comment]
old issue. Maybe check for updated versions? This thread has not been updated in 3 years. Closing issue. If the issue persists, please open a new one.
