### ISSUE TITLE
Request:  option to disable new shells starting in newest bookmark

### ISSUE THREAD

**Issue by bryanbecker** [oh-my-fish/theme-budspencer#31]
For my workflow, I prefer new shells to open in $HOME, and to use bookmarks just for commonly used, but inconvenient to type directories.

Requesting a configuration variable to disable this behavior

**Comment by tannhuber** [comment]
Put this into your `config.fish`:
```
set -l index (contains -i $HOME $bookmarks)
if [ $index -gt 0 ^ /dev/null ]                                                                                                        
    set -e bookmarks[$index] 
end
set bookmarks $HOME $bookmarks
```
It will make $HOME the first item in your bookmarks list.

**Comment by bryanbecker** [comment]
That works, but why not just modify `fish_prompt.fish` to add lines 864 and 856 (probably a better variable name could be used)

```fish
847 # Cd to newest bookmark if this is a login shell
848 if not begin
849     set -q -x LOGIN
850     or set -q -x RANGER_LEVEL
851     or set -q -x VIM
852   end ^ /dev/null
853   if set -q bookmarks[1]
854     if not set -q budspencer_noautoopenbookmarks
855       cd $bookmarks[1]
856     end
857   end
858 end
859 set -x LOGIN $USER
```

**Comment by tannhuber** [comment]
Hi @bryanbecker: I agree with you. Perhaps, I'll make it configurable in the future. However, it's a very special request. My bookmarks haven't changed for a long time. And I've $HOME as first bookmark item, as well. For the moment, it's important that there's also a solution for your workflow.

**Comment by mellotanica** [comment]
i agree with @bryanbecker, i just keep removing the
` if set -q bookmarks[1]
    cd $bookmarks[1]
 end`
lines after each update..
i find it useful to have the terminal emulator suggest the starting directory, for example using terminator and splitting the view or opening a new tab, most of the times i need to open another shell in the same directory as i was before to edit something not far away

**Comment by chrisbutler** [comment]
i'd make a PR for this unless anyone else with more direct knowledge can do it

**Comment by clayauld** [comment]
Contemplating adding this feature. I will update status when I have time.

**Comment by clayauld** [comment]
Added this option. See updated README. The new option can be set by adding this to your init.fish:

```
set -U budspencer_no_cd_bookmark
```
