### ISSUE TITLE
Killing shell does not terminate child processes

### ISSUE THREAD

**Issue by raphael-costa** [oh-my-fish/theme-budspencer#33]
I originally mistakenly filed this upstream, you can watch me embarrassing myself [here](https://github.com/fish-shell/fish-shell/issues/3155).

Opening for example `ranger` and closing the terminal will leave `fish` and `ranger` both open, except that instead of looking for files `ranger` will now be hunting your CPU usage.

This is caused by the ["Termination" section](https://github.com/oh-my-fish/theme-budspencer/blob/master/fish_prompt.fish#171-177) of fish_prompt.fish.

**Comment by tannhuber** [comment]
Interesting, I observed this behavior, as well. But I thought it was a ranger issue. However, I'm not sure that budspencer is the culprit. It seems to happen also with an empty termination function and a different theme. Try the following with the default theme:
```
function ontermination -s HUP -s INT -s QUIT -s TERM --on-process %self
end
ranger
```
Close the terminal. What happens?

**Comment by raphael-costa** [comment]
You are right, that function is causing the issue.

**Comment by krader1961** [comment]
I see that the [actual]( https://github.com/oh-my-fish/theme-budspencer/blob/master/fish_prompt.fish#171-177) `ontermination` function calls `__budspencer_detach_session`. However, if that function doesn't do the equivalent of `builtin exit` it will leave the shell running; quite possibly spinning and chewing up CPU time.

**Comment by tannhuber** [comment]
Obviously I don't understand how it works. The desired behavior would be to execute `__budspencer_detach_session` if the terminal is closed (SIGHUP delivered). So, I tried:
```
function __budspencer_on_termination -s HUP --on-process %self -d 'Execute when shell terminates'
  set -l item (contains -i %self $budspencer_sessions_active_pid ^ /dev/null)                                                      
  __budspencer_detach_session $item
  exit
end
```
But it doesn't work.

**Comment by raphael-costa** [comment]
@tannhuber By the way, are sessions even working? I was trying to debug the problem but they don't seem to do anything at all.

**Comment by tannhuber** [comment]
@raphael-costa Sessions work very well for me. Or do you mean the SIGSPEC feature of fish's functions? That's something I obviously don't understand in detail. Hopefully @krader1961 can help.

**Comment by clayauld** [comment]
Old issue. If this still is a problem please reopen or open a new issue.
