### ISSUE TITLE
Consider 2-line prompt

### ISSUE THREAD

**Issue by Dietr1ch** [oh-my-fish/theme-budspencer#34]
It may be good to consider using a multi-line prompt

```
1  ✔                                                               19:36:23  ~
command
output
```

This seems cleaner and allows to copy the whole line to get the command,
 as no extra characters appear on the line.
Otherwise Normal mode could yank the command on `yy`, but still this allows
 to copy commands and their output easily.

Using this requires using `\e[1A` and `\e[1B` to move the cursor up and down on the right prompt, which may not work fine on every shell and will require this to be optional.

**Comment by tannhuber** [comment]
Why not? I see the benefit. However, I'm very busy. Let's keep it open for the moment. I'll think about it.

**Comment by clayauld** [comment]
Old request.... right now we are going to keep using a single line. This is a specific request. If you would like to add this feature you can go ahead and fork the repo and create a PR to merge the changes.
