### ISSUE TITLE
Printing weird character before the terminal arrow which is on the left side.

### ISSUE THREAD

**Issue by Eta-Meson** [oh-my-fish/theme-budspencer#35]
After updating to the latest fish version there is a weird character printed before the terminal (=>) symbol.

**Comment by tannhuber** [comment]
Hi,

what does `functions fish_mode_prompt` tell you?

**Comment by Eta-Meson** [comment]
I am on Arch linux I downgraded the package to fish, version 2.3.0 .Yesterday .
The problem seem to be gone after I update it again today. 
How ever The out put of `functions fish_mode_prompt` in this theme is 

`function fish_mode_prompt
	# Turns off mode indicator
end
` 

The output of the same in other themes like bob the fish is

`function fish_mode_prompt --description 'Displays the current mode'
	# Do nothing if not in vi mode
  if test "$fish_key_bindings" = "fish_vi_key_bindings"
    switch $fish_bind_mode
      case default
        set_color --bold --background red white
        echo '[N]'
      case insert
        set_color --bold --background green white
        echo '[I]'
      case replace-one
        set_color --bold --background green white
        echo '[R]'
      case visual
        set_color --bold --background magenta white
        echo '[V]'
    end
    set_color normal
    echo -n ' '
  end
end
`

And the enter still does not work with the latest fish version 2.3.1 . You cannot press enter with out a command .

**Comment by tannhuber** [comment]
Newer fish versions define an ugly vi mode indicator in `fish_mode_prompt`. It was fixed by @raphael-costa, see #29. I thought this might have been the weird character you mentioned above.

The theme doesn't do anything if you press enter in a command line containing nothing or whitespace characters only. That's different from other shell prompts. The philosophy behind budspencer is to show only important things.

**Comment by Eta-Meson** [comment]
Thank you, you can close this issue now.

On Tue, Jul 5, 2016, 9:16 PM tannhuber <notifications@github.com> wrote:

> Newer fish versions define an ugly vi mode indicator in fish_mode_prompt.
> It was fixed by @raphael-costa <https://github.com/raphael-costa>, see #29
> <https://github.com/oh-my-fish/theme-budspencer/pull/29>. I thought this
> might have been the weird character you mentioned above.
>
> The theme doesn't do anything if you press enter in a command line
> containing nothing or whitespace characters only. That's different from
> other shell prompts. The philosophy behind budspencer is to show only
> important things.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/oh-my-fish/theme-budspencer/issues/35#issuecomment-230518071>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AHe8JrI1Rg5JdhosaSPPW7lfLOSYElAJks5qSnxfgaJpZM4JD_Tm>
> .
>
-- 
K. Mohan Sai Krishna
Roll No: 130101039
Computer Science and Engineering
IIT Guwahati
India

**Comment by tannhuber** [comment]
You're welcome.
