### ISSUE TITLE
No binding found for sequence “\nbind -M visual ”

### ISSUE THREAD

**Issue by Alsan** [oh-my-fish/theme-budspencer#38]
I get the "No binding ..." message everytime when I start a new terminal session after switch to fisherman from omf and install budspencer as plugin. So, how can I get rid this message? Thanks.

**Comment by DictatorBob** [comment]
I've observed this too. To fix it, edit $HOME/.config/fish/functions/fish_user_key_bindings.fish

When fisherman adds the budspencer config to this file, for some reason, it starts out like this:

    ### budspencer ###
    set fish_key_bindings fish_vi_key_bindings
    bind '
bind -M visual '
    bind ' ' __budspencer_toggle_pwd
    bind -M visual ' ' __budspencer_toggle_pwd
    bind L __budspencer_cd_next
    bind H __budspencer_cd_prev
    bind m mark
    bind M unmark
    bind . __budspencer_edit_commandline
    bind -M insert \r __budspencer_preexec
    bind \r __budspencer_preexec
    ### budspencer ###

If you comment out (or delete) these two lines:
    bind '
bind -M visual '

you won't see that message any more. I'm not sure why unbalanced quotes are getting dropped in there. I suspect something lost in translation between the omf install and the fisherman install.

**Comment by w1k1n9cc** [comment]
The results from the two lines

    bind '#' __budspencer_toggle_symbols
    bind -M visual '#' __budspencer_toggle_symbols

in [key_bindings.fish](https://github.com/oh-my-fish/theme-budspencer/blob/master/key_bindings.fish).
I think that this is a result from the parsing process because comments will be ignored.

**Comment by bitsofinfo** [comment]
can this please be fixed in the main distro?

**Comment by clayauld** [comment]
This issue appears to be fixed.
