### ISSUE TITLE
After switching to this theme shell stopped responding

### ISSUE THREAD

**Issue by tomleo** [oh-my-fish/theme-budspencer#4]
I switched to this theme and now my shell isn't responding. I tried changing to shell being used via the config file, but I still can't spawn new shells.

**Comment by jscheel** [comment]
I believe you have to set vi mode.

**Comment by bpinto** [comment]
That seems right. Could you confirm it was missing? @tomleo

**Comment by tannhuber** [comment]
I think, it's solved. @tomleo: Feel free to reopen if the problem still occurs.
