### ISSUE TITLE
fish: Unknown command '__budspencer_preexec'

### ISSUE THREAD

**Issue by Ramblurr** [oh-my-fish/theme-budspencer#42]
enabling budspencer, then opening a new fish session results in this error and a hang when executing any command: 

```
fish: Unknown command '__budspencer_preexec'
```

I have added the following line to the beginning of my `$OMF_CONFIG/init.fish`

```
 set -U fish_key_bindings fish_vi_key_bindings
```

Any idea what's up?

**Comment by stephane-r** [comment]
Same problem .. no solution ?

**Comment by fourcolors** [comment]
I have the same problem here. I was using `fisher` to install the theme however. Could that make the difference?

**Comment by AdwinKing** [comment]
Duplicate of # 47

**Comment by clayauld** [comment]
Issue should be resolved after new updates.

**Comment by mmsaeed509** [comment]
## I didn't find a solution to this issue

![Screenshot_17](https://user-images.githubusercontent.com/62524855/146954932-0afbb836-5467-48d4-aacd-41291c7825e4.png)
