### ISSUE TITLE
Clearing terminal after special commands execution

### ISSUE THREAD

**Issue by ghost** [oh-my-fish/theme-budspencer#43]
Hey,

After I execute commands like `m` or `d` the console is not cleared as expected (see https://asciinema.org/a/f0d0gn6wdsj8206gbwp3uan7u).

I was trying to tweak the lines responsible for the issue but I didn't manage to get it working:

    for i in (seq (expr $num_items + 1))
        tput cuu1
    end
    tput ed
    tput cuu1

Any ideas what's the problem? I guess `tput ed` is not working for me for some reason...

I use fish 2.3.0, iTerm 3.0.10/Terminal 2.6.1, OS X 10.11.6

**Comment by clayauld** [comment]
Are you still getting this issue?

**Comment by clayauld** [comment]
No response
