### ISSUE TITLE
there is some issue with [URxvt] [i3] [Arch] switching to  fullscreen back to normal.

### ISSUE THREAD

**Issue by narutowindy** [oh-my-fish/theme-budspencer#45]
![2017-01-03-202008_1366x768_scrot](https://cloud.githubusercontent.com/assets/18193527/21611668/d0b9a068-d1f3-11e6-9caa-83372afbb2d8.png)

see they are _**not aligned properly**_.  it seems very minute but i _**couldn't find solution on net**_ so i have no choice to ask here.

i am a "biginner/Intermediate Linux user"

**Comment by bobthecow** [comment]
This is a limitation of all terminals. The only way to avoid it is not to have a "right prompt". Or to clear your screen after you resize :)
