### ISSUE TITLE
Problem with $pwd_style

### ISSUE THREAD

**Issue by michaeltarleton** [oh-my-fish/theme-budspencer#46]
I'm getting the following error after installing:

```
~/.config/fish/functions/fish_prompt.fish (line 20):   switch $pwd_style
                                                              ^
in function '__budspencer_prompt_bindmode'
	called on line 864 of file ~/.config/fish/functions/fish_prompt.fish

in command substitution
	called on line 862 of file ~/.config/fish/functions/fish_prompt.fish

in function 'fish_prompt'
	called on standard input

in command substitution
	called on standard input
```

I have installed using `fisher install oh-my-fish/theme-budspencer`.

**Comment by michaeltarleton** [comment]
It looks like $pwd_style is not being set before multiple switch statements are called

**Comment by ehausen** [comment]
A fix for this?

**Comment by clayauld** [comment]
I'm not seeing this issue at all. Can you tell me what your setup looks like? OS version, fish version, etc...

**Comment by MartinDelille** [comment]
I had this issue on *MacOS 10.14.6* with fish 3.0.2 just after installing the theme.

Starting a new fish session fixed it.

**Comment by clayauld** [comment]
If your issue is fixed may I close this?

**Comment by MartinDelille** [comment]
Yes

**Comment by MartinDelille** [comment]
There is still something quite annoying: when I type a command, it works but I can hear the *Funk* alert sound (I found the name by testing the alert sounds in *System preferences > Sound > Sound effects).

I also have this problem when trying to start help:

```
$ budspencer_help
The file /themes/budspencer/README.md does not exist.
```

**Comment by clayauld** [comment]
You'll need to set the bell off by adding ```set -U budspencer_nobell`` to your init.fish file. The ```budspencer help`` issue tells me your $OMF_PATH variable isn't set right. You'll need to examine your OMF installation to figure out why that isn't happening.

**Comment by MartinDelille** [comment]
Ok I installed *theme-budspencer* with [fisher](https://github.com/jorgebucaran/fisher/) which explains why I don't have the `$OMF_PATH` set.

Since I don't have `init.fish` file, I add `set -U budspencer_nobell` at the beginning of the `config.fish` and it fixed the problem. The strange thing is that removing this line didn't restore the alert sound.

By curiosity: I'm wondering what is the purpose of playing this *Funk* sound alert after each command? Since this specific sound is associated to an error, it's like something is going wrong.

**Comment by clayauld** [comment]
I'm not sure what the reasoning was to have the bell played after each command. That was a decision made before I was added as maintainer. I may disable that in the future, depending on how many issues are raised about it.

The ```set -U budspencer_nobell``` command sets a universal config that is kept across all sessions from that point forward. The ```set -U``` functionality of fish sets that flag and means the command has to only be run once, not each time a session is opened. See https://fishshell.com/docs/current/commands.html#set for more details on how this all works.

A way you can work around your issue for the $OMF_PATH variable is add it as a variable and point it to the location fisher installs your theme or plugin. Off the top of my head I don't know where that is, but OMF usually installs it to ```~/.local/share/omf``` on Linux. I'm not sure where that location is on Mac.

**Comment by MartinDelille** [comment]
Ok thanks for the clarification about `set -U`!

It seems fisher just fetch the fish files so the README isn't store anywhere and thus won't work with fisher installation. It isn't a big problem by the way.

**Comment by clayauld** [comment]
Sounds good. I'll close this issue unless you need more clarification.
