### ISSUE TITLE
use with Fira Code

### ISSUE THREAD

**Issue by jorda0mega** [oh-my-fish/theme-budspencer#49]
Is there a way to integrate Fira Code into this theme similar to the bobthefish theme? It has some nice icons and ligatures for Git.
![image](https://user-images.githubusercontent.com/484084/30778711-b41210a4-a0aa-11e7-8f50-9687d0fae253.png)
VS.
![image](https://user-images.githubusercontent.com/484084/30778718-c036208c-a0aa-11e7-9ede-275e63c6a970.png)

**Comment by clayauld** [comment]
Are you attempting to set your terminal to use the Fira Code font? That should allow you to see the icons and ligatures as you expect.
