### ISSUE TITLE
Missing signs

### ISSUE THREAD

**Issue by lehnavid** [oh-my-fish/theme-budspencer#50]
![bildschirmfoto 2017-11-11 um 13 37 59](https://user-images.githubusercontent.com/25310004/32689461-9dd8b93a-c6e5-11e7-8f03-e00cc4d85ea3.png)

As you can see my shell don't get the correct presentation for this theme and shows some "?". Anyone know's what causes this problem?

I installed it via this guide: https://github.com/ellerbrock/fish-shell-setup-osx

**Comment by janernsting** [comment]
Your fonts aren't powerline patched: https://github.com/powerline/fonts
