### ISSUE TITLE
Is this project alive?

### ISSUE THREAD

**Issue by bitsofinfo** [oh-my-fish/theme-budspencer#51]
Was looking at the PR's and issues, is this project still alive?

**Comment by sagebind** [comment]
This particular theme is quite old and does not currently have an active maintainer.

**Comment by clayauld** [comment]
Is there any interest of someone else taking over this repository as the maintainer? I'm interested in improving some functionality and merging the PRs as well as closing some of the issues.

**Comment by bobthecow** [comment]
@clayauld Are you volunteering? 🙂

**Comment by clayauld** [comment]
@bobthecow Yes I am, in fact!

**Comment by bobthecow** [comment]
@clayauld I've added you as a maintainer!
