### ISSUE TITLE
Random Green Colored lines on Powerline

### ISSUE THREAD

**Issue by DakshMiglani** [oh-my-fish/theme-budspencer#53]
![](https://i.imgur.com/JCnUiZN.png)
So, the powerline has some random green colored lines? I'm not sure if it's a font issue, but I'm using DejaVu Sans Mono Nerd Font Edition.

**Comment by DakshMiglani** [comment]
![Image of the terminal](https://i.imgur.com/JCnUiZN.png)

**Comment by Shub1427** [comment]
It's a Font issue, that happens in Linux Terms. Did you resolved it anyhow? @DakshMiglani
