### ISSUE TITLE
color palette

### ISSUE THREAD

**Issue by ahmadrezash** [oh-my-fish/theme-budspencer#59]
Hi
Tnx for your theme
I don't like your default color palette of this theme but I can't find anyone new.
How I can do that. A new color palette for this them.
 Please help me...

**Comment by clayauld** [comment]
Color palate can be changed by adding this to your init.fish:

```
set -U budspencer_colors 000000 666666 1c50f7 ffffff ffff00 ff6600 ff0000 ff0033 3300ff 00aaff 00ffff 00ff00
```

You can use sites like this to check color codes: https://htmlcolorcodes.com/
