### ISSUE TITLE
does only work with en_US.UTF-8 locale

### ISSUE THREAD

**Issue by poel22** [oh-my-fish/theme-budspencer#65]
If I change to any different locale from another country, i have weird errors and can't see the status infos (i.e. cwd) anymore. It also happens if I only set LC_TIME to something else, indicating it may has something to do with the time format.

**Comment by clayauld** [comment]
Do you have a log of the error or an output of what the error says?

**Comment by poel22** [comment]
Sorry for not adding right away, lazy me ...

On boot there actually is no error, just the terminal is blank without any prompt. I can type just fine though. To reproduce it should be sufficient to add LC_TIME other than main language to /etc/locale.conf (and apply by rebooting). I cant reproduce the error output right now, but i now think its a issue with fish and not with the theme, because other themes wont work either. It does also not matter if i use st or xfce4-terminal. I will report this in the main fish repo later on.

**Comment by poel22** [comment]
`LC_TIME=en_UK.UTF-8 fish` when my locale is `en_US.UTF-8`

actually even this call is sufficient for me to either fix or brake it.

**Comment by poel22** [comment]
its an omf issue actually, i already opened a bug report.

**Comment by clayauld** [comment]
Glad you got it figured out!
