### ISSUE TITLE
Installing + Uninstalling This Theme Does Not Remove Settings

### ISSUE THREAD

**Issue by bonedaddy** [oh-my-fish/theme-budspencer#66]
I've been exploring a wide variety of fish themes, and was testing out budspencer. After testing, I removed the theme and discovered that the settings it change weren't reverted back. In particular:

* Fish prompt was not reverted
* Key bindings were not reverted

**Comment by clayauld** [comment]
Did you set your fish theme to something else to override settings? I've been able to switch to a different theme after using the budspencer theme.

If you have errors or outputs of logs, etc please post those.

**Comment by clayauld** [comment]
I tested this several times on a fresh install of Ubuntu 20.04 and haven't found any issues. Can you let me know if you are experiencing any issues still? If I don't get a response in a week I'll be closing this issue.

**Comment by clayauld** [comment]
No response. Closing issue.
