### ISSUE TITLE
How to Disable edit-commandline function?

### ISSUE THREAD

**Issue by Naolador** [oh-my-fish/theme-budspencer#68]
The shortcut of edit-commandline function is conflict when I pressing "esc"+"." in shell, this key combination is very useful to append previous parameters. However, the edit-commandline function shares the same shortcut.

How to disable or edit the edit-commandline shortcut?

**Comment by clayauld** [comment]
I'm curious what function you're using to implement the edit-commandline feature? I may want to integrate that to my shell. 

Either way, you can change your key bindings using this documentation: https://fishshell.com/docs/current/cmds/bind.html

For example, I'm setting a custom user key binding in my init.fish using this function:
```fish
function fish_user_key_bindings
      for mode in insert default visual
          bind -M $mode \cf forward-char
      end
    end
```

This little snippet sets the key binding for all modes available in theme-budspencer.

**Comment by Naolador** [comment]
Thanks for the documentation. I found the meta key discussed in the last paragraph was quite helpful. I can use "alt"+"." to avoid the conflict on switching between vi editing modes with the "esc" key.

**Comment by clayauld** [comment]
Did you get it figured out as you needed then? If so I'll close the issue. Let me know if you need more help.

**Comment by Naolador** [comment]
All good, thank you. I also opened another issue regards to switching directories with H and L key but the right segment section won't reflect the directory that I will go. Do you have any ideas?

**Comment by clayauld** [comment]
I'll take a look at it in that issue thread. I'll close this one now.
