### ISSUE TITLE
function erron on OSx

### ISSUE THREAD

**Issue by ciscohack** [oh-my-fish/theme-budspencer#74]
Hi Team,

I have installed budspencer theme on my macos fish shell. but I am getting an error while running some of function like d and c.

here is the error for function c but I am having error for d function too. help me to fix this problem or if is code issue please fix it. thanks 

fish: Unknown command: xsel
~/.local/share/omf/themes/budspencer/fish_prompt.fish (line 320):

**Comment by clayauld** [comment]
This is likely not an issue with the them. Did you just start using the fish shell? It is likely that the command "xsel" you are trying to use is not in your PATH, and can't be found by the the fish shell.

**Comment by clayauld** [comment]
Closing due to no response. The issue is not with the theme, but with the lack of the proper command in the PATH.
