### ISSUE TITLE
Cannot install on macOS

### ISSUE THREAD

**Issue by Soromeister** [oh-my-fish/theme-budspencer#85]
Hello, I have tried installing the theme on a macOS using the steps outlined in the readme. That is, I have added the required lines to the config.fish and I have coreutils, gnu-sed, git, xsel, wmctrl and taskwarrior installed and added to path.

After doing an $ omf install budspencer, I am greeted with:

"fish: Unknown command: __budspencer_preexec"

I am unable to proceed further as I am getting that error every time I try to run a command in fish, including omf, basically bricking my omf installation. This persists in new fish instances.

**Comment by scorphus** [comment]
Are you able to run `omf update`?

**Comment by Soromeister** [comment]
I am able to run `omf update`

**Comment by scorphus** [comment]
Please, try installing the theme after issuing `omf update`.
